# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmoketest():
  def setup_method(self, method):
    options = Options()
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_smoketest(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.title == "Teton Idaho CoC"

  def test_home_page_features(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "nav ul")
    assert len(elements) > 0
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".main-spotlight > div")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".main-spotlight > div")
    assert len(elements) == 3
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".main-hero .a-button")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".main-hero .a-button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".join-wizard-main h3").text == "Welcome to the Teton Chamber of Commerce Signup Wizard!"

  def test_directory_page(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.ID, "directory-grid")))
    self.driver.find_element(By.ID, "directory-grid").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#directory-data section")))
    elements = self.driver.find_elements(By.XPATH, "//div[@id='directory-data']//p[contains(text(),'Teton Turf and Tree')]")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-list").click()
    elements = self.driver.find_elements(By.XPATH, "//div[@id='directory-data']//p[contains(text(),'Teton Turf and Tree')]")
    assert len(elements) > 0

  def test_join_page(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=fname]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input[name=fname]").send_keys("Juan")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=lname]").send_keys("Reyes")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=bizname]").send_keys("Test Business")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=biztitle]").send_keys("Owner")
    self.driver.find_element(By.CSS_SELECTOR, "input[value='Next Step']").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=email]")
    assert len(elements) > 0

  def test_admin_login(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").send_keys("baduser")
    self.driver.find_element(By.ID, "password").send_keys("badpassword")
    self.driver.find_element(By.CSS_SELECTOR, ".login input.mysubmit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
